# Generated by Django 3.2.3 on 2021-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('link', models.URLField()),
                ('date', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Data1',
        ),
    ]
