# Generated by Django 3.2.3 on 2021-07-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20210724_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexDisplay',
        ),
    ]
